# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4afa2b49e48eff59d6eae1d0a991792e"
name = "Helixo-countdown-timer-app"
application_url = "https://ecommerce-functions-soc-rugs.trycloudflare.com"
embedded = true
handle = "helixo-countdown-timer-app"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ecommerce-functions-soc-rugs.trycloudflare.com/auth/callback",
  "https://ecommerce-functions-soc-rugs.trycloudflare.com/auth/shopify/callback",
  "https://ecommerce-functions-soc-rugs.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://ecommerce-functions-soc-rugs.trycloudflare.com"
subpath = "helixo-timer"
prefix = "apps"

[pos]
embedded = false
