[[extensions]]

uid = "92fd871f-a502-eaef-9c4a-e22e0527824049196e8e"

type = "theme"
name = "timer-widget"
handle = "timer-widget"
extension_points = ["product", "product_template", "collection", "index", "page"]